name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
      - 'release'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set working directory
      run: cd C:/Users/goldi/OneDrive/Bilder/FH/3.Semester/DevOps/assignment1/DevOpsAssignment1/web-app/web-app/blog
      shell: bash

    - run: npm install
    - run: npm run lint

  # ... (other job configurations)

  push:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set working directory
      run: cd C:/Users/goldi/OneDrive/Bilder/FH/3.Semester/DevOps/assignment1/DevOpsAssignment1/web-app/web-app/blog
      shell: bash

    - run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
    - run: docker build -t web-app .
    - run: docker tag web-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/web-app:latest
    - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/web-app:latest
