name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
      - 'release'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
      working-directory: /home/runner/work/DevOpsAssignment1/web-app/web-app/blog
    - run: npm run lint
      working-directory: /home/runner/work/DevOpsAssignment1/web-app/web-app/blog


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t web-app .

  audit:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm audit

  push:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set working directory
      run: cd /home/runner/work/DevOpsAssignment1/web-app/web-app/blog
      shell: bash

    - run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
    - run: docker build -t web-app .
    - run: docker tag web-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/web-app:latest
    - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/web-app:latest
      working-directory: /home/runner/work/DevOpsAssignment1/web-app/web-app/blog
