name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
      - 'release'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      working-directory: web-app/web-app/blog
      run: |
        npm install
        npm install eslint  # Install ESLint

        - name: Setup ESLint Configuration
      working-directory: web-app/web-app/blog
      run: |
        echo "module.exports = {" > .eslintrc.js
        echo "  root: true," >> .eslintrc.js
        echo "  parser: 'babel-eslint'," >> .eslintrc.js
        echo "  extends: ['eslint:recommended']," >> .eslintrc.js
        echo "  rules: {" >> .eslintrc.js
        echo "    // Add specific rules here, if needed" >> .eslintrc.js
        echo "  }," >> .eslintrc.js
        echo "};" >> .eslintrc.js

    - name: Lint
      working-directory: web-app/web-app/blog
      run: |
        npm run lint

  push:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set working directory
      run: cd /home/runner/work/DevOpsAssignment1/web-app/web-app/blog
      shell: bash

    - run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
    - run: docker build -t web-app .
    - run: docker tag web-app:latest ${{ secrets.DOCKER_HUB_USERNAME }}/web-app:latest
    - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/web-app:latest
